name: NiceGuyWinning
favicon: null
layout_spectrum: 0.25423
typography_spectrum: 0.00867
title: Nice Guy Winning
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c0c0e'
    - '#b4d6fc'
    - '#67372b'
    - '#cc906e'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
